import { Roboto } from 'next/font/google';
import './globals.css';

const font = Roboto({
  weight: ['400', '700'],
  subsets: ['cyrillic']
});

export const metadata = {
  title: 'Custom IDE',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${font.className} mainWrap`}>
        {children}
      </body>
    </html>
  );
}
